openapi: 3.0.0
info:
  title: ThingsPro Device API
  version: 0.0.1
servers:
  - url: https://{ip}:{port}/api/v1
    variables:
      ip:
        default: 127.0.0.1
        description: HTTPs Server IP of Device
      port:
        default: '8443'
        description: HTTPs Server Port of Device
security:
  - auth: []
paths:
  /device/general:
    get:
      description: Get system general configuration.
      tags:
        - general
      responses:
        '200':
          description: System general configuration.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralInformation'
              example:
                data:
                  description: This is My Thingspro Edge.
                  hostName: Moxa
                  modelName: UC-8112A-ME-T-LX-EU
                  serialNumber: IMOXA1234567
                  firmwareVersion: 1.0.0
                  softwareVersion: 1.0.0
                  biosVersion: 1.0.0S01
                  lastBootTime: '2019-06-27T10:10:16+08:00'
                  memorySize: 1056120832
                  cpu: ARMv7 Processor rev 2 (v7l)
                  disk:
                    - name: System
                      mount: /
                      device: /dev/root
                      total: 3206059008
                      free: 1905097752
                      used: 1138657820
                      percent: 35.5
                      tags:
                        used: systemDiskUsed
                        free: systemDiskFree
                        percent: systemDiskPercent
    patch:
      tags:
        - general
      description: Update system general configuration.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                description:
                  type: string
                  description: This is My Thingspro Edge.
                  maximum: 512
                  example: MyThingsproEdge
                hostName:
                  type: string
                  description: device hostname. <br> - Hostname must be between 1 and 64 octets inclusive.<br> - Each label in the hostname (component separated by ".") must be between 1 and 63 octets inclusive. <br> - Each label must start with an ASCII alphabet character (a-z, A-Z), end with an ASCII alphanumeric character (a-z, A-Z, 0-9), and must contain only ASCII alphanumeric characters or hyphens (a-z, A-Z, 0-9, "-").
                  minimum: 1
                  maximum: 64
                  pattern: ^[a-zA-Z]([a-zA-Z0-9-]*[a-zA-Z0-9])?(\.[a-zA-Z]([a-zA-Z0-9-]*[a-zA-Z0-9])?)*$
                  example: Moxa
            examples:
              update device display name:
                value:
                  description: This is My Thingspro Edge.
              update device hostname:
                value:
                  hostName: MyHost
      responses:
        '200':
          description: System general configuration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralInformation'
              example:
                data:
                  description: This is My Thingspro Edge.
                  hostName: MyHost
                  modelName: UC-8112A-ME-T-LX-EU
                  serialNumber: IMOXA1234567
                  firmwareVersion: 1.0.0
                  softwareVersion: 1.0.0
                  biosVersion: 1.0.0S01
                  lastBootTime: '2019-06-27T10:10:16+08:00'
                  memorySize: 1056120832
                  cpu: ARMv7 Processor rev 2 (v7l)
                  disk:
                    - name: System
                      mount: /
                      device: /dev/root
                      total: 3206059008
                      free: 1905097752
                      used: 1138657820
                      percent: 35.5
                      tags:
                        used: systemDiskUsed
                        free: systemDiskFree
                        percent: systemDiskPercent
  /device/time:
    get:
      description: Get system time configuration.
      tags:
        - time
      responses:
        '200':
          description: Device time configuration.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimeInformation'
              example:
                data:
                  lastUpdateTime: '-'
                  time: '2015-03-26T16:27:48+08:00'
                  timezone: Asia/Taipei
                  ntp:
                    enable: false
                    source: timeserver
                    server: time.cloudflare.co
                    interval: 86400
    patch:
      tags:
        - time
      description: Update system time configuration.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TimeInformation'
            examples:
              update time (manual):
                value:
                  time: '2015-03-26T16:27:48+08:00'
              update timezone:
                value:
                  timezone: Asia/Taipei
              sync time from NTP time server:
                value:
                  ntp:
                    enable: true
                    source: timeserver
                    server: time.cloudflare.com
                    interval: 6000
      responses:
        '200':
          description: Device time configuration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimeInformation'
              example:
                data:
                  lastUpdateTime: '-'
                  time: '2015-03-26T16:27:48+08:00'
                  timezone: Asia/Taipei
                  ntp:
                    enable: false
                    source: timeserver
                    server: pool.ntp.org
                    interval: 86400
  /device/zoneinfo:
    get:
      tags:
        - time
      description: Get current timezone information
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimezoneInfo'
components:
  securitySchemes:
    auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    GeneralInformation:
      title: System general configuration
      properties:
        description:
          type: string
          description: device description.
          minLength: 0
          maxLength: 512
          example: This is My Thingspro Edge.
        hostName:
          type: string
          description: device hostname. <br> - Hostname must be between 1 and 64 octets inclusive.<br> - Each label in the hostname (component separated by ".") must be between 1 and 63 octets inclusive. <br> - Each label must start with an ASCII alphabet character (a-z, A-Z), end with an ASCII alphanumeric character (a-z, A-Z, 0-9), and must contain only ASCII alphanumeric characters or hyphens (a-z, A-Z, 0-9, "-").
          minLength: 1
          maxLength: 64
          pattern: ^[a-zA-Z]([a-zA-Z0-9-]*[a-zA-Z0-9])?(\.[a-zA-Z]([a-zA-Z0-9-]*[a-zA-Z0-9])?)*$
          example: Moxa
        modelName:
          type: string
          description: Model name of device.
          minLength: 1
          maxLength: 255
          readOnly: true
          example: UC-8100A-ME-T-LX
        serialNumber:
          type: string
          description: Serial number of device.
          minLength: 12
          maxLength: 12
          readOnly: true
          example: IMOXA1234567
        softwareVersion:
          type: string
          description: Product package version.
          minLength: 5
          maxLength: 255
          readOnly: true
          example: 2.0.0-1600
        firmwareVersion:
          type: string
          description: device firmware version.
          minLength: 3
          maxLength: 255
          readOnly: true
          example: '1.0'
        biosVersion:
          type: string
          description: device BIOS/Bootloader version.
          minLength: 3
          maxLength: 255
          readOnly: true
          example: 1.0.0S06
        memorySize:
          type: integer
          description: device memory size(unit:byte).
          minimum: 1
          maximum: 2147483647
          readOnly: true
          example: 2116034560
        cpu:
          type: string
          description: device cpu information.
          minLength: 1
          maxLength: 255
          readOnly: true
          example: ARMv7 Processor rev 5 (v7l)
        disk:
          type: array
          description: device disk information.
          readOnly: true
          items:
            type: object
            readOnly: true
            properties:
              name:
                type: string
                description: disk name.
                minLength: 1
                maxLength: 255
                readOnly: true
                example: System
              mount:
                type: string
                description: disk mount point
                minLength: 1
                maxLength: 255
                readOnly: true
                example: /
              device:
                type: string
                description: disk physical device node path
                minLength: 1
                maxLength: 255
                readOnly: true
                example: /dev/root
              total:
                description: 'disk Total size (unit: byte)'
                type: integer
                minimum: 1
                maximum: 18446744073709552000
                readOnly: true
                example: 6948147200
              free:
                description: 'disk Free size (unit: byte)'
                type: integer
                minimum: 1
                maximum: 18446744073709552000
                readOnly: true
                example: 4857821184
              used:
                description: 'disk Used size (unit: byte)'
                type: integer
                minimum: 1
                maximum: 18446744073709552000
                readOnly: true
                example: 1798492160
              percent:
                description: Percent of used size
                type: number
                minimum: 0
                maximum: 100
                readOnly: true
                example: 27.019343397064695
              tags:
                type: object
                readOnly: true
                properties:
                  used:
                    type: string
                    readOnly: true
                    example: systemDiskUsed
                  free:
                    type: string
                    readOnly: true
                    example: systemDiskFree
                  percent:
                    type: string
                    readOnly: true
                    example: systemDiskPercent
        lastBootTime:
          type: string
          description: |
            device last boot time. (format in RFC 3339)
            ('2020-06-04T5:45:44Z or '2020-06-04T13:45:44.000+08:00')
          minLength: 20
          maxLength: 29
          readOnly: true
          example: '2020-06-04T13:45:44+08:00'
    TimeInformation:
      title: System time configuration
      properties:
        lastUpdateTime:
          type: string
          description: |
            Last update time with RFC3339 format after time settings.
            '-' means not updated yet since NTP updated and enabled.
          readOnly: true
          example: '2015-03-26T16:00:00+08:00'
        time:
          type: string
          description: 'Current system time (format: RFC3339).'
          minLength: 20
          maxLength: 35
          example: '2015-03-26T16:27:48+08:00'
        timezone:
          type: string
          description: device timezone.
          minLength: 1
          maxLength: 64
          example: Asia/Taipei
        ntp:
          type: object
          properties:
            enable:
              type: boolean
              description: enable/disable sync time from time server
              example: false
            source:
              type: string
              description: time sync source
              enum:
                - timeserver
              default: timeserver
            server:
              type: string
              description: ntp server url
              minLength: 2
              maxLength: 253
              pattern: (?=^.{2,253}$)(?:^(?!\.|-)[a-zA-Z0-9\-]{0,62}[a-zA-Z0-9])(?:\.(?!\.|\-)[a-zA-Z0-9\-]{0,62}[a-zA-Z0-9])*$
              example: pool.ntp.org
            interval:
              type: integer
              description: ntpd update interval
              minimum: 60
              maximum: 2592000
              example: 7200
    TimezoneInfo:
      description: Timezone information
      type: object
      required:
        - zone
        - iso3166
      properties:
        zone:
          description: TZ zone list with cca2 and TZ
          readOnly: true
          type: array
          items:
            description: ISO 3166 alpha-2 country code and zone name
            type: object
            required:
              - cca2
              - name
              - offset
            properties:
              cca2:
                description: ISO 3166 alpha-2 country code
                type: string
                pattern: '[A-Z]{2}'
              name:
                description: zone name
                type: string
              offset:
                description: zone offset (format should be "+0800", etc)
                type: string
        iso3166:
          description: ISO 3166 alpha-2 country codes
          readOnly: true
          type: array
          items:
            description: ISO 3166 alpha-2 country code and country name
            type: object
            required:
              - cca2
              - name
            properties:
              cca2:
                description: ISO 3166 alpha-2 country code
                type: string
                pattern: '[A-Z]{2}'
              name:
                description: The usual English name for the coded region
                type: string
      example:
        data:
          zone:
            - cca2: AD
              name: Europe/Andorra
              offset: '+0100'
            - cca2: AE
              name: Asia/Dubai
              offset: '+0400'
            - cca2: AF
              name: Asia/Kabul
              offset: '+0430'
          iso3166:
            - cca2: AD
              name: Andorra
            - cca2: AE
              name: United Arab Emirates
            - cca2: AF
              name: Afghanistan
